### ISSUE TITLE
Congratulations on your first repository!

### ISSUE THREAD

**Issue by sivar2311** [mjtrini/sinric-pro-garage-controller#1]
Congratulations on your first repository!

Please change the file extension to .ino - then the code display will be coloured accordingly.

Please adjust the line breaks. 
Sometimes there are several lines of source code in only one line - this makes it very difficult to read.

Can you write the code for the gate a little more abstractly?
My recommendation would be to write a function for opening the gate and one for closing it, e.g. like this:
```C++
void open_gate() {
  digitalWrite(....
  ...
}

void close_gate() {
  digitalWrite(....
  ...
}
```

These functions can then be reused later by your web server as well as by the SinricPro code and the meaning is clear from the code.

```C++
bool onDoorState(const String& deviceId, bool &state) {
  if (state == true) close_gate();
  if (state == false) open_gate();
  return true;
}
```

**Comment by mjtrini** [comment]
Hi, thanks for the feedback. I uploaded a sketch created by Rui Santos for ease of readability. If it is possible to insert Sinric pro garagedoor or switch into the sketch without causing the esp8266 to crash (mine crashes after a few seconds of connecting to my router). If we can get this to work I am going to purchase additional devices on your sinric pro site for use in device I intend to deploy.

**Comment by sivar2311** [comment]
>  I uploaded a sketch created by Rui Santos for ease of readability

Which sketch do you mean?
There is no code change in the repository yet. 
Or did I misunderstood?

>  If it is possible to insert Sinric pro garagedoor or switch into the sketch without causing the esp8266 to crash (mine crashes after a few seconds of connecting to my router)

Did you find the reason for these crashes?

**Comment by sivar2311** [comment]
> Hi, I just checked and the revised code is in the repository. I have also attached it here in the reply as a zip file.

Oh, now I see that it's a sketch by Rui Santos - I hadn't noticed that before.
I had understood that you had already implemented my advice regarding readability and modularity.
Unfortunately, I can't yet see what the code does - except run a WebServer.

>  Have you had success using sinric pro on an esp8266 running a webserver?


Yes, a web server (including the AsyncWebServer) can be used simultaneously with SinricPro without any problems. I have already used this successfully in the past. Somewhere in the already closed issues in the SinricPro repository there are also sample codes.

**Comment by sivar2311** [comment]
AsyncWebserver (webinterface) + SinricPro: [SinricPro issue #166 comment #9](https://github.com/sinricpro/esp8266-esp32-sdk/issues/166#issuecomment-808856420)

**Comment by mjtrini** [comment]
Hi your webserver worked perfectly in issue#166. The sketch from Rui Santos is a webserver with  sliding buttons to control LEDs wired to the esp8266. Is it possible to implant the sinric pro code into his sketch? That way I can easily build from there.

**Comment by sivar2311** [comment]
I think first of all we should come back to your original question. This was "Can you provide the code to set the digital pins on the esp8266 to activate a garage door wall switch and also to read the garage open closed state?"

But now you are looking at merging a web server example.

I don't know your programming skills but simply mixing several examples will lead nowhere.

Therefore, I recommend taking small steps.

Please define your goal first, so I can get a better idea. What do you want to achieve? Why do you need a web server (for example, I'm not quite sure yet)?

Step 1: Program functions to control / query the gate.
Step 2: Implement SinricPro
These two steps refer to your original request.

Step 3, 4 etc.: Improve / extend (e.g. to include your desired web server).

**Comment by mjtrini** [comment]
Hi,
You are quiet correct in the mixing of examples. I have deployed several gate and garage controllers based on the esp8266. They are accessed locally via their onboard webserver (useful when Internet is not available). Also they can be accessed anywhere in the world using Telegram to send commands to each controller unit and read the status of the reed switch for the gate/garage closed position.

I now wish to use the sinric pro garagedoor code to allow voice control from the Amazon alexa app. I have used an example sketch of the sinric pro switch and it works great. Ideally i would like an example of the garagedoor code to show placement of the gpio pins for sending motor commands and reading the closed position status.

The biggest roadblock for me is the implanting of the sinric pro example code into my esp8266 based gate /garage controller units. The esp8266 running the async webserver simply crashes. I should have laid out my problem from the start, so my apologies there.

The sketch from Ruis Santos is very similiar to my webserver however it is properly formatted and not as complex in functionality. If the sinric pro switch or garagedoor example code can be safely implanted into his sketch, that would immediately solve my issue. From there I can make the necessary changes to my sketch.

Thanking you for all your assistance so far!

**Comment by sivar2311** [comment]
I don't think it will be that difficult.

As I wrote before, if you abstract the control and query functions for the gate into separate functions, everything can be combined very easily. The same functions can be used by SinricPro, the WebInterface, Telegram etc.

You don't need to define GPIOs for SinricPro. SinricPro does not even know GPIOs (and that is precisely the advantage of the system). SinricPro exclusively takes care of communication with Alexa / Google Home etc.

Can you provide the functions for opening, closing and querying the gate? Please write a simple example with 3 functions for your gate:
open_gate, close_gate, query_gate_state (ok, maybe you can think of better names ;).

Here are some (clean code style) code snippets from a project i am working on (it's a gate controller too):

Gate.ino
```C++
#include <Arduino.h>
#include <WiFi.h>

#include "config.h"
#include "ble_remote.h"
#include "credentials.h"
#include "gate.h"
#include "sinric.h"

void setup_wifi() {
    Serial.println("[WiFi]: initializing");

//  ESP32 Arduino 1.x
//    WiFi.onEvent([](system_event_id_t event) { Serial.println("[WiFi]: connected"); }, SYSTEM_EVENT_STA_GOT_IP);
//    WiFi.onEvent([](system_event_id_t event) { Serial.println("[WiFi]: disconnected"); }, SYSTEM_EVENT_STA_DISCONNECTED);

//  ESP32 Arduino 2.x
    WiFi.onEvent([](arduino_event_id_t event) { Serial.println("[WiFi]: connected"); }, ARDUINO_EVENT_WIFI_STA_GOT_IP);
    WiFi.onEvent([](arduino_event_id_t event) { Serial.println("[WiFi]: disconnected"); }, ARDUINO_EVENT_WIFI_STA_DISCONNECTED);

    Serial.println("[WiFi]: connecting...");
    WiFi.begin(WIFI_SSID, WIFI_PASS);
}

void setup() {
    Serial.begin(SERIAL_BAUD_RATE);
    Serial.setDebugOutput(true);
    setup_the_gate();
    setup_ble_remote();
    setup_wifi();
    setup_sinricpro();
}

void loop() {
    SinricPro.handle();
    stop_the_gate_when_the_gate_is_fully_open_or_closed();
    handle_ble_remote();
    handle_clear_button();
}
```

gate.h
```C++
#pragma once

#include "config.h"

void setup_the_motors() {
    Serial.println("[Gate]: setting up motors");
    pinMode(GPIO_MOTOR_OPEN, PINMODE_MOTORS);
    pinMode(GPIO_MOTOR_CLOSE, PINMODE_MOTORS);

    digitalWrite(GPIO_MOTOR_OPEN, !MOTOR_ACTIVE_LEVEL);
    digitalWrite(GPIO_MOTOR_CLOSE, !MOTOR_ACTIVE_LEVEL);
}

void setup_the_limitswitches() {
    Serial.println("[Gate]: setting up limit switches");
    pinMode(GPIO_LIMITSWITCH_OPEN, PINMODE_LIMITSWITCHES);
    pinMode(GPIO_LIMITSWITCH_CLOSE, PINMODE_LIMITSWITCHES);
}

void setup_the_gate() {
    setup_the_motors();
    setup_the_limitswitches();
}

void open_the_gate() {
    Serial.println("[Gate]: opening the gate...");
    digitalWrite(GPIO_MOTOR_OPEN, MOTOR_ACTIVE_LEVEL);
    digitalWrite(GPIO_MOTOR_CLOSE, !MOTOR_ACTIVE_LEVEL);
}

void close_the_gate() {
    Serial.println("[Gate]: closing the gate...");
    digitalWrite(GPIO_MOTOR_OPEN, !MOTOR_ACTIVE_LEVEL);
    digitalWrite(GPIO_MOTOR_CLOSE, MOTOR_ACTIVE_LEVEL);
}

bool the_gate_is_opening() {
    return digitalRead(GPIO_MOTOR_OPEN) == MOTOR_ACTIVE_LEVEL;
}

bool the_gate_is_not_opening() {
    return !the_gate_is_opening();
}

bool the_gate_is_closing() {
    return digitalRead(GPIO_MOTOR_CLOSE) == MOTOR_ACTIVE_LEVEL;
}

bool the_gate_is_not_closing() {
    return !the_gate_is_closing();
}

bool the_gate_is_moving() {
    return (the_gate_is_opening() || the_gate_is_closing());
}

bool the_gate_is_not_moving() {
    return !the_gate_is_moving();
}

bool the_gate_is_fully_open() {
    return digitalRead(GPIO_LIMITSWITCH_OPEN) == LIMITSWITCH_ACTIVE_LEVEL;
}

bool the_gate_is_not_fully_open() {
    return !the_gate_is_fully_open();
}

bool the_gate_is_fully_closed() {
    return digitalRead(GPIO_LIMITSWITCH_CLOSE) == LIMITSWITCH_ACTIVE_LEVEL;
}

bool the_gate_is_not_fully_closed() {
    return !the_gate_is_fully_closed();
}

void stop_the_gate() {
    digitalWrite(GPIO_MOTOR_OPEN, !MOTOR_ACTIVE_LEVEL);
    digitalWrite(GPIO_MOTOR_CLOSE, !MOTOR_ACTIVE_LEVEL);
    Serial.println("[Gate]: stopped");
    if (the_gate_is_fully_open()) Serial.println("[Gate]: is fully open.");
    if (the_gate_is_fully_closed()) Serial.println("[Gate]: is fully closed.");
}

void stop_the_gate_when_the_gate_is_fully_open_or_closed() {
    if (the_gate_is_closing() && the_gate_is_fully_closed()) stop_the_gate();
    if (the_gate_is_opening() && the_gate_is_fully_open()) stop_the_gate();
}
```

The many small abstractions not only allow you to reuse the code at any point. It also increases readability and allows you to write almost human-readable code:
`if (the_gate_is_closing() && the_gate_is_fully_closed()) stop_the_gate();` can be understood even by a non-programmer. The reader doesn't even have to worry about the GPIOs. They only appear in the more detailed levels.

**Comment by sivar2311** [comment]
Sorry, i had forgotten to post "sinric.h":

sinric.h
```C++
#pragma once

#include "SinricPro.h"
#include "SinricProLock.h"
#include "credentials.h"
#include "gate.h"

SinricProLock& lock = SinricPro[DEVICE_ID];

bool handle_sinricpro_command(const String& deviceId, bool& command) {
    bool close = true;
    bool open = false;

    if ((command == open) && the_gate_is_not_fully_open()) open_the_gate();
    if ((command == close) && the_gate_is_not_fully_closed()) close_the_gate();

    return true;
}

void setup_sinricpro() {
    lock.onLockState(handle_sinricpro_command);
    SinricPro.onConnected([]() { Serial.println("[SinricPro]: connected"); });
    SinricPro.onDisconnected([]() { Serial.println("[SinricPro]: disconnected"); });

    Serial.println("[SinricPro]: connecting...");
    SinricPro.begin(APP_KEY, APP_SECRET, "testws.sinric.pro");
}
```

Note: This gate controller is based on SinricProLock device instead of SinricProGaragedoor

**Comment by mjtrini** [comment]
Hey thanks for the code snippets! I will clean up my code first before sending you the sketch. I did notice that when i attempted static ip settings on your sinric pro webserver code, the webserver started however it could not connect to the sinric pro website. Perhaps that is what crashes my sketch when I implanted the sinric pro switch code. I will experiment a bit  while cleaning up the sketch and let you know!

**Comment by sivar2311** [comment]
Hm, I have not yet experienced a crash due to (incorrectly?) configured static IP settings. But the error is sometimes in the detail. First try it with the "normal" dynamic IP settings. If everything works, we can take a look at the static settings later and go troubleshooting.

It's late and I'll call it a day. 
I will be "online" again in about 8 hours :)

**Comment by mjtrini** [comment]
Hi morning. I found the reason for sinric pro crashing. The section in void loop for the ctbot code to handle messages caused the instability. Also sinric pro apparently does not like static ip addresses. 

Removing the telegram code from void loop and using dynamic ip address has allowed sinric pro to work. Thank you for all your effort on this issue! I will close the issue now since I can progress a bit with the product.
